name: Email on pull request

on:
  pull_request:
    branches:
      - main

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: arpan@2pirad.com
          password: wbjvldpcnqgbcpmy
          subject: Pull request on main branch
          to: jblarpan.global@gmail.com
          body: |
            Hi,

            There is a new pull request on ABTESTForked the main branch.

            Please review it and let me know if you have any questions.

            Thanks,
            [JBLarpan]

